version: '2'
services:
  sallefy-app:elasticsearch.yml
    image: sallefy
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://sallefy-mysql:3306/sallefy?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://sallefy-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://sallefy-elasticsearch:9200
    ports:
      - 8080:8080
  sallefy-mysql:
    extends:
      file: mysql.yml
      service: sallefy-mysql
  sallefy-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: sallefy-elasticsearch
